window.SUPABASE_URL = 'https://bryegtpdjqpwtyefoznq.supabase.co';
window.SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyeWVndHBkanFwd3R5ZWZvem5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI0OTIwMzQsImV4cCI6MjA5ODA2ODAzNH0.348rGiyn6n3TMZ_I5fayRclAagSB70_d4CrEUtcJU5k';
